version: '3.8'

services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '4000:4000'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 30s
      timeout: 10s
      retries: 3